language: node_js
# node 版本
node_js:
  - 12.8.1
os:
  - windows
# 只监听主分支
branches:
  only:
    - master
    - test
# 缓存
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
# 装依赖
install:
  - yarn
# 运行脚本
script:
  - yarn build
  #- sh ./deploy.sh
# 部署
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # travis-ci.org 中设置的环境变量
  on:
    branch: master