// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconCarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconFlatUiPc: typeof import('~icons/flat-ui/pc')['default']
    IconFxemojiMonkeyface: typeof import('~icons/fxemoji/monkeyface')['default']
    IconFxemojiMonkeysee: typeof import('~icons/fxemoji/monkeysee')['default']
    IconLogosVue: typeof import('~icons/logos/vue')['default']
    IconNotoV1ManTechnologistLightSkinTone: typeof import('~icons/noto-v1/man-technologist-light-skin-tone')['default']
    YoungContextMenu: typeof import('./components/YoungContextMenu/index.vue')['default']
    YoungDialog: typeof import('./components/YoungDialog/index.vue')['default']
    YoungEditor: typeof import('./components/YoungEditor/index.vue')['default']
    YoungImgUpload: typeof import('./components/YoungImgUpload/index.vue')['default']
    YoungPagination: typeof import('./components/YoungPagination/index.vue')['default']
    YoungSlideVerify: typeof import('./components/YoungSlideVerify/index.vue')['default']
    YoungSvg: typeof import('./components/YoungSvg/index.vue')['default']
    YoungTable: typeof import('./components/YoungTable/index.vue')['default']
    YoungTabs: typeof import('./components/YoungTabs/index.vue')['default']
  }
}

export { }
